# Generated by Django 2.0.13 on 2019-02-16 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('done', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('done', models.BooleanField()),
                ('rubric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='just_do_it.Rubric')),
            ],
        ),
        migrations.AddField(
            model_name='target',
            name='task',
            field=models.ForeignKey(on_delete='Цель удалена', to='just_do_it.Task'),
        ),
    ]
