# Generated by Django 2.0.13 on 2019-02-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('just_do_it', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='rubric',
            field=models.CharField(choices=[('READ', 'Прочитать'), ('BUY', 'Купить'), ('TO_DO', 'Сделать'), ('OTHER', 'Другое')], default='OTHER', max_length=10),
        ),
        migrations.DeleteModel(
            name='Rubric',
        ),
    ]
