# Generated by Django 2.0.13 on 2019-02-16 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('just_do_it', '0002_auto_20190216_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='just_do_it.Target'),
        ),
    ]
