# Generated by Django 2.0.13 on 2019-02-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('just_do_it', '0004_auto_20190216_1837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['start_date']},
        ),
    ]
