# Generated by Django 2.0.13 on 2019-02-25 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('just_do_it', '0005_auto_20190220_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='done',
            new_name='complete',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='done',
            new_name='complete',
        ),
    ]
